server:
  port: 9000
spring:
  application:
    name: clean-system-service

  datasource:
    druid:
      filters: stat,slf4j  # 启用日志过滤器
      filter:
        slf4j:
          enabled: true
          statement-executable-sql-log-enable: true  # 关键：显示完整SQL
          statement-log-enabled: true
  redis:
    host: localhost
    port: 6379
    database: 0
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
      application:
        name: demo-service
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
      config:
        namespace: public
        server-addr: localhost:8848

management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

tlog:
  pattern: $preApp-$preHost-$preIp-$spanId-$traceId


#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
#mybatis:
#  configuration:
#    use-actual-param-name: true
