spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    # 数据库连接池配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      filters: stat,slf4j
      filter:
        slf4j:
          enabled: true
          statement-executable-sql-log-enable: true
          statement-log-enabled: true
  application:
    name: clean-inventory-service
  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 3000
  # 注册中心配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
        ephemeral: false
      config:
        namespace: public
        server-addr: localhost:8848

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-actual-param-name: true
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 8001

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
