spring:
  datasource:
    url: jdbc:postgresql://172.20.10.6:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      id-type: auto