#server:
#  port: 9001
#spring:
#  application:
#    name: clean-monitor-service
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        namespace: public
#    loadbalancer:
#      cache:
#        ttl: 5s
#
##  security:
##   user:
##     name: admin
##     password: 123456
spring:
  boot:
    admin:
      ui:
        external-views:
          - label: "Nacos 控制台"
            url: http://localhost:8848/nacos
            order: 100
boot:
  admin:
    discovery:
      enabled: true
      ignored-services: "clean-monitor-service"


alert:
  metrics:
    enabled: true
    threshold: 10
    interval: 5000  # 检查间隔（毫秒）
    recipients:
      - admin@example.com