KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-pass"
    user_admin="admin-pass"
    user_producer="prod-pass"
    user_consumer="cons-pass";
};