server:
  port: 9001
spring:
  application:
    name: clean-example-service
  redis:
    host: localhost
    port: 6379
    database: 0
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
      application:
        name: demo-service
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public
      config:
        namespace: public
        server-addr: localhost:8848

management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

tlog:
  pattern: $preApp-$preHost-$preIp-$spanId-$traceId

rocketmq:
  name-server: localhost:9876
  producer:
    group: ${spring.application.name}
    send-message-timeout: 10000  # 增加超时时间


